version: 2.1

common_defaults: &common_defaults
  docker:
    - image: docker:20.10.14

commands:
  build_and_test:
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Docker image
          command: |
            docker build -t ${DEPLOY_BASE_DOCKER_ACCOUNT_ID}/deployment-base:${CIRCLE_SHA1:0:10} .

      - run:
          name: Test Docker image
          command: |
            docker run --rm \
              -v "$(pwd)/tests.sh":/tmp/tests.sh \
              "${DEPLOY_BASE_DOCKER_ACCOUNT_ID}/deployment-base:${CIRCLE_SHA1:0:10}" \
              /bin/bash tests.sh

      - run:
          name: Create Docker image archive
          command: |
            mkdir /tmp/artifacts
            docker image save -o "/tmp/artifacts/${DEPLOY_BASE_DOCKER_ACCOUNT_ID}-deployment-base-${CIRCLE_SHA1:0:10}.tar" \
              "${DEPLOY_BASE_DOCKER_ACCOUNT_ID}/deployment-base:${CIRCLE_SHA1:0:10}"

      - persist_to_workspace:
          root: /tmp
          paths:
            - artifacts/*

  publish:
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ./

      - run:
          name: Load Docker image from build_and_test workspace
          command: |
            docker image load -i "artifacts/${DEPLOY_BASE_DOCKER_ACCOUNT_ID}-deployment-base-${CIRCLE_SHA1:0:10}.tar"

      - run:
          name: Tag Docker image as latest
          command: |
            docker tag "${DEPLOY_BASE_DOCKER_ACCOUNT_ID}/deployment-base:${CIRCLE_SHA1:0:10}" \
              "${DEPLOY_BASE_DOCKER_ACCOUNT_ID}/deployment-base:latest"

      - run:
          name: Login to DockerHUB
          command: |
            echo "${DEPLOY_BASE_DOCKER_PASS}" | docker login --username ${DEPLOY_BASE_DOCKER_ACCOUNT_ID} --password-stdin

      - run:
          name: Push images to DockerHUB
          command: |
            docker push "${DEPLOY_BASE_DOCKER_ACCOUNT_ID}/deployment-base:${CIRCLE_SHA1:0:10}"
            docker push "${DEPLOY_BASE_DOCKER_ACCOUNT_ID}/deployment-base:latest"

jobs:
  build_and_test_docker_image:
    <<: *common_defaults
    steps:
      - build_and_test
  publish_docker_image:
    <<: *common_defaults
    steps:
      - publish

workflows:
  build-and-publish:
    jobs:
      - build_and_test_docker_image
      - hold:
          type: approval
          requires:
            - build_and_test_docker_image
          filters:
            branches:
              only:
                - master
      - publish_docker_image:
          requires:
            - hold
